### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by KawaiiTemDev** [YARC-Official/YARG-Launcher#10]
Hello there!

i tried compiling this myself because I wanted to make some changes to the UI, but the thing just doesn't run and I get an error that it's not compatible.
![image](https://github.com/YARC-Official/YARG-Launcher/assets/25987110/e6c7f157-a426-4ae0-8d04-500d0ed4883b)

any help?
thank you :)

**Comment by EliteAsian123** [comment]
Hi, are you using `npm run dev`?

If so, what architecture of windows are you using? Thanks!

**Comment by KawaiiTemDev** [comment]
hello! 
I ran  `npm run dev` to preview my changes in the browser and ran `npm run tauri build` afterwards.
I'm running Windows 10 home, 64 bit.

**Comment by EliteAsian123** [comment]
`npm run dev` *should* be opening up a test application window. Are there any errors?

**Comment by KawaiiTemDev** [comment]
![image](https://github.com/YARC-Official/YARG-Launcher/assets/25987110/9bd9dba4-5123-444c-a33a-52b5401f82f5)
this happens, nothing further

**Comment by EliteAsian123** [comment]
Seems like you have the wrong version of Rust installed. Try reinstalling for your proper architecture (64-bit as you've mentioned).

**Comment by KawaiiTemDev** [comment]
![image](https://github.com/YARC-Official/YARG-Launcher/assets/25987110/e0d26b37-085d-4f17-b5d7-c4fe885530b3)
Yet still, no luck :(

**Comment by EliteAsian123** [comment]
Are you 100% sure you are running x86 64-bit, and not, let's say, ARM 64-bit? This error should only occur if you are building for the wrong platform.

**Comment by KawaiiTemDev** [comment]
Fairly..??

If this helps;

![image](https://github.com/YARC-Official/YARG-Launcher/assets/25987110/66acb0f1-15ef-4cb1-9193-5354b5152d57)

**Comment by KawaiiTemDev** [comment]
Not to be that guy, but i somehow managed to fix it..?? xd
I followed stuff from this https://tauri.app/v1/guides/getting-started/prerequisites/#1-microsoft-visual-studio-c-build-tools
